// // This file is generated automatically by Next.js
// // Do not edit this file manually
// // This file validates that all pages and layouts export the correct types



// type PagesPageConfig = {
//   default: React.ComponentType<any> | ((props: any) => React.ReactNode | Promise<React.ReactNode> | never | void)
//   getStaticProps?: (context: any) => Promise<any> | any
//   getStaticPaths?: (context: any) => Promise<any> | any
//   getServerSideProps?: (context: any) => Promise<any> | any
//   getInitialProps?: (context: any) => Promise<any> | any
//   /**
//    * Segment configuration for legacy Pages Router pages.
//    * Validated at build-time by parsePagesSegmentConfig.
//    */
//   config?: {
//     maxDuration?: number
//     runtime?: 'edge' | 'experimental-edge' | 'nodejs' | string // necessary unless config is exported as const
//     regions?: string[]
//   }
// }






// // Validate ../../../pages/404.tsx
// {
//   type __IsExpected<Specific extends PagesPageConfig> = Specific
//   const handler = {} as typeof import("../../../404.tsx")
//   type __Check = __IsExpected<typeof handler>
//   // @ts-ignore
//   type __Unused = __Check
// }

// // Validate ../../../pages/_app.tsx
// {
//   type __IsExpected<Specific extends PagesPageConfig> = Specific
//   const handler = {} as typeof import("../../../pages/_app.js")
//   type __Check = __IsExpected<typeof handler>
//   // @ts-ignore
//   type __Unused = __Check
// }

// // Validate ../../../pages/_document.tsx
// {
//   type __IsExpected<Specific extends PagesPageConfig> = Specific
//   const handler = {} as typeof import("../../../pages/_document.js")
//   type __Check = __IsExpected<typeof handler>
//   // @ts-ignore
//   type __Unused = __Check
// }

// // Validate ../../../pages/cart.tsx
// {
//   type __IsExpected<Specific extends PagesPageConfig> = Specific
//   const handler = {} as typeof import("../../../pages/cart.js")
//   type __Check = __IsExpected<typeof handler>
//   // @ts-ignore
//   type __Unused = __Check
// }

// // Validate ../../../pages/index.tsx
// {
//   type __IsExpected<Specific extends PagesPageConfig> = Specific
//   const handler = {} as typeof import("../../../pages/index.js")
//   type __Check = __IsExpected<typeof handler>
//   // @ts-ignore
//   type __Unused = __Check
// }

// // Validate ../../../pages/partner-preferences.tsx
// {
//   type __IsExpected<Specific extends PagesPageConfig> = Specific
//   const handler = {} as typeof import("../../../pages/partner-preferences.js")
//   type __Check = __IsExpected<typeof handler>
//   // @ts-ignore
//   type __Unused = __Check
// }

// // Validate ../../../pages/product/[id].tsx
// {
//   type __IsExpected<Specific extends PagesPageConfig> = Specific
//   const handler = {} as typeof import("../../../pages/product/[id].js")
//   type __Check = __IsExpected<typeof handler>
//   // @ts-ignore
//   type __Unused = __Check
// }

// // Validate ../../../pages/video/[id].tsx
// {
//   type __IsExpected<Specific extends PagesPageConfig> = Specific
//   const handler = {} as typeof import("../../../pages/video/[id].js")
//   type __Check = __IsExpected<typeof handler>
//   // @ts-ignore
//   type __Unused = __Check
// }




